language: node_js
sudo: false
node_js:
- '4.4.7'
before_script:
- npm install mocha
script:
- node_modules/.bin/mocha
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: A9/4gKzFcYrPjEXzuV8t0uADGNtr+EjNbGci4po6AOvbQLCWQQEvpv9Nqs1AeHQSqCNL8ekvC4gzV3SOlSYBw4LXKPrPJM9VVInqYInqHuuiqhEE7L2eMxiCq27tvW3KadEl6sMUTiqfnk3LtCRizLvVC52V5KcZkLUphU8Jy5w=
  on:
    tags: true
    repo: DracoBlue/jsb
    all_branches: true
    node: 4.4.7
